name: Docker Workflow

on:
  push:
    branches:
      - kotlin_

jobs:
  build-and-run:
    name: Docker run workflow
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

############################### Java ###############################
      - name: Build Application docker - 1
        run: |
          docker build -t simple-http-server-kotlin .
          # docker run -p 8080:8080 simple-http-server-kotlin
          docker tag simple-http-server-kotlin sreedockerhub19/simple-http-server-kotlin:latest
          docker push sreedockerhub19/simple-http-server-kotlin:latest